// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xrfaptpqlllibcopnzdm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhyZmFwdHBxbGxsaWJjb3BuemRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2NTg5MjgsImV4cCI6MjA3MTIzNDkyOH0.K9qdrv1LxDd4TetXWux39ll0Ba-LDETOrrRlzfq4Jr8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});